### ISSUE TITLE
Module Knowledge Odoo v10....need help

### ISSUE THREAD

**Issue by MakMas** [OCA/knowledge#126]
Hello,

I'm new here, can some one help me with this module?
I'm migrate two weeks ago on the Odoo v.10 and I need module Knowledge on my system.
I'm downloaded module Knowledge from this link https://github.com/OCA/knowledge/tree/10.0/document_url and copy to my folder with another modules. When I try to install this module i have many different mistake.....maybe I do something wrong?

Traceback (most recent call last):
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/datadrive/odoo/odoo_10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/datadrive/odoo/odoo_10/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/datadrive/odoo/odoo_10/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/datadrive/odoo/odoo_10/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/datadrive/odoo/odoo_10/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/datadrive/odoo/odoo_10/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/datadrive/odoo/odoo_10/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/datadrive/odoo/odoo_10/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/datadrive/odoo/odoo_10/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/datadrive/odoo/odoo_10/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/datadrive/odoo/odoo_10/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/datadrive/odoo/odoo_10/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 549, in _tag_menuitem
    group_id = self.id_get(group)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 785, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 791, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/datadrive/odoo/odoo_10/odoo/addons/base/ir/ir_model.py", line 1033, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-5>", line 2, in xmlid_lookup
  File "/datadrive/odoo/odoo_10/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/datadrive/odoo/odoo_10/odoo/addons/base/ir/ir_model.py", line 1022, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: knowledge.group_document_user" while parsing /datadrive/odoo/addons-custom/knowledge10/views/knowledge.xml:34, near
<menuitem id="menu_document_root" name="Knowledge" groups="base.group_system,knowledge.group_document_user" sequence="116"/>

**Comment by max3903** [comment]
Thanks @MakMas 

Are you trying to install knowledge or knowledge_url?

knowledge_url is not migrated yet. You can review it here: #111 
knowledge is already migrated and should be working. Otherwise, please copy/paste here the error messages you get.

**Comment by MakMas** [comment]
I'am try to install: Knowledge Management System

and in Odoo i have this mistake:

Traceback (most recent call last):
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/datadrive/odoo/odoo_10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/datadrive/odoo/odoo_10/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/datadrive/odoo/odoo_10/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/datadrive/odoo/odoo_10/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/datadrive/odoo/odoo_10/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/datadrive/odoo/odoo_10/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/datadrive/odoo/odoo_10/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/datadrive/odoo/odoo_10/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/datadrive/odoo/odoo_10/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/datadrive/odoo/odoo_10/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/datadrive/odoo/odoo_10/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/datadrive/odoo/odoo_10/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/datadrive/odoo/odoo_10/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 549, in _tag_menuitem
    group_id = self.id_get(group)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 785, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/datadrive/odoo/odoo_10/odoo/tools/convert.py", line 791, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/datadrive/odoo/odoo_10/odoo/addons/base/ir/ir_model.py", line 1033, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-5>", line 2, in xmlid_lookup
  File "/datadrive/odoo/odoo_10/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/datadrive/odoo/odoo_10/odoo/addons/base/ir/ir_model.py", line 1022, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: knowledge.group_document_user" while parsing /datadrive/odoo/addons-custom/knowledge10/views/knowledge.xml:34, near
<menuitem id="menu_document_root" name="Knowledge" groups="base.group_system,knowledge.group_document_user" sequence="116"/>

**Comment by MakMas** [comment]
Everything good, its my mistake....I'am try to install wrong module.
Thank you very much  for your help!
