### ISSUE TITLE
error on instalation in ODoo 10

### ISSUE THREAD

**Issue by ilyasProgrammer** [OCA/knowledge#145]
Empty database. Trying to install knowledge module. Got this:

```
 Traceback (most recent call last):
  File "/pd/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/pd/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/pd/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/pd/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/pd/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/pd/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/pd/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/pd/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/pd/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/pd/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/pd/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/pd/odoo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/pd/odoo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/pd/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/pd/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/pd/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/pd/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/pd/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/pd/odoo/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/pd/odoo/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/pd/odoo/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/pd/odoo/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/pd/odoo/odoo/addons/base/ir/ir_model.py", line 1192, in _update
    record = record.create(values)
  File "/pd/odoo/odoo/addons/base/ir/ir_ui_view.py", line 353, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/pd/odoo/odoo/models.py", line 3818, in create
    self._fields[key].determine_inverse(record)
  File "/pd/odoo/odoo/fields.py", line 999, in determine_inverse
    getattr(records, self.inverse)()
  File "/pd/odoo/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/pd/odoo/odoo/addons/base/ir/ir_ui_view.py", line 371, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/pd/odoo/odoo/models.py", line 3550, in write
    self._write(old_vals)
  File "/pd/odoo/odoo/models.py", line 3696, in _write
    self._validate_fields(vals)
  File "/pd/odoo/odoo/models.py", line 1074, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Model not found: knowledge.config.settings

>Error context:
View `Configure Knowledge`
[view_id: 206, xml_id: n/a, model: knowledge.config.settings, parent_id: n/a]
None" while parsing /pd/OCA/knowledge/knowledge/views/res_config.xml:4, near
```xml
<record id="view_knowledge_configuration" model="ir.ui.view">
    <field name="name">Configure Knowledge</field>
    <field name="model">knowledge.config.settings</field>
    <field name="arch" type="xml">
      <form string="Configure Knowledge" class="oe_form_configuration">
        <header>
          <button string="Apply" type="object" name="execute" class="oe_highlight"/>
          or
          <button string="Cancel" type="object" name="cancel" class="oe_link"/>
        </header>
        <separator string="Knowledge and Documents Management"/>
        <group>
          <label for="id" string="Documents"/>
          <div>
            <div>
              <field name="module_document" class="oe_inline"/>
              <label for="module_document"/>
            </div>
            <div>
              <field name="module_document_page" class="oe_inline"/>
              <label for="module_document_page"/>
            </div>
            <div>
              <field name="module_document_page_approval" class="oe_inline"/>
              <label for="module_document_page_approval"/>
            </div>
          </div>
        </group>
        <separator string="Connect with an external DMS"/>
        <group>
          <label for="id" string="Using CMIS"/>
          <div>
            <div>
              <field name="module_cmis_read" class="oe_inline"/>
              <label for="module_cmis_read"/>
            </div>
            <div>
              <field name="module_cmis_write" class="oe_inline"/>
              <label for="module_cmis_write"/>
            </div>
          </div>
        </group>
      </form>
    </field>
  </record>
```

**Comment by max3903** [comment]
@ilyasProgrammer Seems like the model is not created. Can you try restarting Odoo and installing the module?

**Comment by ilyasProgrammer** [comment]
Helped pulling clean Odoo from git.
