### ISSUE TITLE
[11.0] document_page: Print Error

### ISSUE THREAD

**Issue by ghost** [OCA/knowledge#177]
`Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_document_page_report_documentpage_doc_525
  File "<template>", line 2, in body_call_content_524
AttributeError: 'document.page' object has no attribute 'display_content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/addons/web/controllers/main.py", line 1617, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/share/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/share/odoo/3rd-enabled/report_xlsx/controllers/main.py", line 43, in report_routes
    reportname, docids, converter, **data
  File "/usr/share/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/share/odoo/odoo/addons/web/controllers/main.py", line 1566, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_actions_report.py", line 628, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_actions_report.py", line 666, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_actions_report.py", line 470, in render_template
    return view_obj.render_template(template, values)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1195, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/share/odoo/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/share/odoo/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1204, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 344, in _compiled_fn
    raise e
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1635_519
  File "<template>", line 2, in body_call_content_518
  File "<template>", line 3, in foreach_517
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 349, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'document.page' object has no attribute 'display_content'
Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_document_page_report_documentpage_doc_525
  File "<template>", line 2, in body_call_content_524
AttributeError: 'document.page' object has no attribute 'display_content'

Error to render compiling AST
AttributeError: 'document.page' object has no attribute 'display_content'
Template: document_page.report_documentpage_doc
Path: /templates/t/t/div/div
Node: <div t-raw="doc.display_content"/>`

**Comment by pedrobaeza** [comment]
Version?

**Comment by ghost** [comment]
sorry. 11.0.

**Comment by pedrobaeza** [comment]
Steps to reproduce? Is reproducible on runbot?

**Comment by ghost** [comment]
yes, it is.
http://3333479-11-0-344f5f.runbot2.odoo-community.org/web?debug=1#id=2&view_type=form&model=document.page&menu_id=88&action=106

**Comment by ghost** [comment]
steps: only try to print document
