### ISSUE TITLE
document_url - Uncaught Promise > Only one conditional branching directive is allowed per node

### ISSUE THREAD

**Issue by eabquina** [OCA/knowledge#508]
## Module
document_url when activated causes error when opening attachment link on the chatter window

```UncaughtPromiseError > OwlError
Uncaught Promise > Only one conditional branching directive is allowed per node
OwlError: Only one conditional branching directive is allowed per node
    Error: Only one conditional branching directive is allowed per node
        at normalizeTIf (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1495:86)
        at normalizeXML (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1502:27)
        at _parse (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1407:22)
        at parse (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1405:37)
        at compile (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1503:49)
        at App._compileTemplate (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1569:300)
        at App.getTemplate (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1161:118)
        at new ComponentNode (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1003:133)
        at https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1549:6
        at Chatter.template (eval at compile (https://localhost:8069/web/assets/1/4694d8f/web.assets_web.min.js:1503:374), <anonymous>:166:23)
```

## Describe the bug

This bug renders the file attachment URL, and relevant buttons like the Send Message and Log Note in the chatter, not workgin

## To Reproduce
**Affected versions**:

1. Install document_url module
2. Open attachments in chatter, or upload a new one 
3.

**Expected behavior**
File Attachment links on the chatter section should be working with no errors

**Additional context**

`Firefox : 132.0.2 (aarch64)`
```
Google Chrome | 130.0.6723.117 (Official Build) (arm64)
```

**Comment by pedrobaeza** [comment]
Do you have an updated browser?

**Comment by eabquina** [comment]
hello @pedrobaeza , capturing Chrome and Firefox versions used to test the issue again now. 

`Firefox : 132.0.2 (aarch64)`


```
Google Chrome | 130.0.6723.117 (Official Build) (arm64)
```

**Comment by pedrobaeza** [comment]
Maybe is this? https://github.com/OCA/knowledge/pull/506
