### ISSUE TITLE
[8.0] TypeError: function lambda at 0x7f1f2cb562a8 is not JSON serializable

### ISSUE THREAD

**Issue by alanljj** [OCA/knowledge#54]
after installed, when click menu Marketing-MassMailing, the message pop

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    return self._json_response(result)
  File "/opt/odoo/openerp/http.py", line 519, in _json_response
    body = simplejson.dumps(response)
  File "/home/odoo/odoo/lib/python2.7/site-packages/simplejson/__init__.py", line 370, in dumps
    return _default_encoder.encode(obj)
  File "/home/odoo/odoo/lib/python2.7/site-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/odoo/odoo/lib/python2.7/site-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/home/odoo/odoo/lib/python2.7/site-packages/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x7f1f2cb562a8> is not JSON serializable

**Comment by pedrobaeza** [comment]
What module have you installed?

**Comment by alanljj** [comment]
the module of document_page

**Comment by akram1** [comment]
Same problem more details as follows:

Error on document_page

Odoo 8 (build 26/7/2015) Ubuntu 14.04, Postgres 9.4.1, werkzeug 0.9.6, Python 2.7.8

On a clean Odoo DB, installing document_page then installing crm_mass_mailing cause marketing manu top menu to stop working and make this error :
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/simplejson/__init__.py", line 370, in dumps
    return _default_encoder.encode(obj)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x7fd348cef410> is not JSON serializable

Odoo terminal shows this:=======================================================================================
2015-07-26 21:39:00,771 27925 INFO 8-1 werkzeug: 127.0.0.1 - - [26/Jul/2015 21:39:00] "POST /im_chat/init HTTP/1.1" 200 -
2015-07-26 21:39:00,819 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:00,823 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:00,828 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:01,165 27925 INFO 8-1 werkzeug: 127.0.0.1 - - [26/Jul/2015 21:39:01] "POST /web/action/load HTTP/1.1" 200 -
2015-07-26 21:39:01,403 27925 INFO ? werkzeug: 127.0.0.1 - - [26/Jul/2015 21:39:01] "GET /web/static/src/img/search_reset.gif HTTP/1.1" 200 -
2015-07-26 21:39:01,497 27925 INFO 8-1 werkzeug: 127.0.0.1 - - [26/Jul/2015 21:39:01] "POST /web/dataset/call_kw/share.wizard/has_share HTTP/1.1" 200 -
2015-07-26 21:39:01,787 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:01,793 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:01,797 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:01,972 27925 INFO 8-1 werkzeug: 127.0.0.1 - - [26/Jul/2015 21:39:01] "POST /web/dataset/call_kw/mail.mass_mailing/fields_view_get HTTP/1.1" 200 -
2015-07-26 21:39:02,009 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:02,012 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:02,014 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:02,131 27925 INFO 8-1 werkzeug: 127.0.0.1 - - [26/Jul/2015 21:39:02] "POST /web/dataset/call_kw/mail.mass_mailing/fields_view_get HTTP/1.1" 200 -
2015-07-26 21:39:02,468 27925 INFO 8-1 werkzeug: 127.0.0.1 - - [26/Jul/2015 21:39:02] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
2015-07-26 21:39:02,551 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:02,555 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:02,556 27925 WARNING 8-1 openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-07-26 21:39:02,634 27925 ERROR 8-1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/simplejson/__init__.py", line 370, in dumps
    return _default_encoder.encode(obj)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")

Uninstalling document_page cuase this error: (uninstallation was seccessful and Marketing works now)====================================================
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by whoople** [comment]
### Same issue

Uninstallation was seccessful and **Mass Mailing** (Marketing menu)  works now and no issue popup.
Thanks for help

...//   2015-09-12 12:52:27,281 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:27,285 2379 ERROR PROD openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/opt/odoo/server/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 321, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 237, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 311, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 213, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x7f6ec80> is not JSON serializable
2015-09-12 12:52:30,912 2379 DEBUG ? openerp.service.server: cron1 polling for jobs
2015-09-12 12:52:34,710 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,710 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,710 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,715 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,716 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,716 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,850 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,851 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,851 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,859 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,860 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,860 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,864 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,865 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,865 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,958 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,959 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,959 2379 WARNING PROD openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-09-12 12:52:34,964 2379 ERROR PROD openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/opt/odoo/server/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 321, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 237, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 311, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 213, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x7f2775690cf8> is not JSON serializable  
//...

**Comment by max3903** [comment]
I can't reproduce on the latest version.

**Comment by ccarly** [comment]
In Marketing&Mass Mailing

```
192.168.254.209 - - [2015-11-10 16:44:40] "POST /web/dataset/call_kw/mail.mass_mailing/fields_view_get HTTP/1.1" 200 5347 0.039534
192.168.254.209 - - [2015-11-10 16:44:40] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 286 0.009001
2015-11-10 16:44:40,974 16727 WARNING mydb openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-11-10 16:44:40,974 16727 WARNING mydb openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-11-10 16:44:40,974 16727 WARNING mydb openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-11-10 16:44:40,978 16727 ERROR mydb openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 354, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 262, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 340, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 239, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x7fb228106b18> is not JSON serializable
192.168.254.209 - - [2015-11-10 16:44:40] "POST /web/dataset/call_kw/mail.mass_mailing/fields_get HTTP/1.1" 200 1587 0.012133

```

**Comment by alanljj** [comment]
new fresh install today, the problem still there:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/opt/odoo/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 354, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 262, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 340, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 239, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x7f37782c9500> is not JSON serializable
